module.exports = {
  result_data: [
    "等待中..",
    "等待重判",
    "编译中",
    "运行并评判",
    "答案正确",
    "格式错误",
    "答案错误",
    "时间超限",
    "内存超限",
    "输出超限",
    "运行错误",
    "编译错误",
    "编译器错误",
  ],
  language_data: [
    "C",
    "C++",
    "Java",
    "Python2",
    "Python3",
    "Switch",
    "C#",
    "Go",
    "Ruby",
    "Bash",
  ],
  language: {
    c: "c",
    cpp: "cpp",
    csharp: "csharp",
    go: "go",
    java: "java",
    javascript: "javascript",
    pascal: "pascal",
    perl: "perl",
    php: "php",
    python: "python",
    r: "r",
    ruby: "ruby",
    rust: "rust",
    swift: "swift",
    vb: "vb"
  },
  editor_config: {
    value: "",
    language: "cpp",
    theme: "vs-dark",
    cursorStyle: "line",
    contextmenu: true,
    automaticLayout: true,
    autoIndent: false,
    lineNumbers: true,
    mouseStyle: "text",
    quickSuggestions: false,
    renderLineHighlight: "none",
    wordWrap: "off",
    stopRenderingLineAfter: -1,
    scrollbar: {
      horizontal: "auto",
      vertical: "hidden",
      verticalScrollbarSize: 0,
    },
    minimap: {
      enabled: false,
    },
    lineDecorationsWidth: 0,
    lineNumbersMinChars: 3,
  },
};
