# Generated by Django 3.2.3 on 2021-05-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='学号/工号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.password', verbose_name='已注册用户')),
                ('real_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='真实姓名')),
                ('nick', models.CharField(blank=True, max_length=24, null=True, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('submit', models.IntegerField(default=0, verbose_name='提交数量')),
                ('solved', models.IntegerField(default=0, verbose_name='解决数量')),
                ('defunct', models.BooleanField(default=0, verbose_name='是否隐藏')),
                ('ip', models.CharField(max_length=46, verbose_name='ip地址')),
                ('access_time', models.DateTimeField(blank=True, null=True, verbose_name='登陆时间')),
                ('reg_time', models.DateTimeField(blank=True, null=True, verbose_name='注册时间')),
                ('school', models.CharField(max_length=20, verbose_name='学校')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('role_pri', models.IntegerField(choices=[(0, '超级管理员'), (1, '管理员'), (2, '教师'), (3, '志愿者'), (4, '用户')], verbose_name='权限')),
                ('is_delete', models.BooleanField(default=0, verbose_name='保护')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50, verbose_name='队伍名')),
                ('school', models.CharField(max_length=50, verbose_name='学校名')),
                ('trainer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_id', to='app.user', verbose_name='指导老师')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_id', to='app.user', verbose_name='队伍成员')),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='题目标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='题目描述')),
                ('input', models.TextField(blank=True, null=True, verbose_name='输入描述')),
                ('output', models.TextField(blank=True, null=True, verbose_name='输出描述')),
                ('sample_input', models.TextField(blank=True, null=True, verbose_name='样例输入')),
                ('sample_output', models.TextField(blank=True, null=True, verbose_name='样例输出')),
                ('spj', models.BooleanField(default=0, verbose_name='是否特判')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='提示')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='来源')),
                ('in_data', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='时间限制')),
                ('memory_limit', models.IntegerField(default=128, verbose_name='空间限制')),
                ('defunct', models.BooleanField(default=0, verbose_name='是否隐藏')),
                ('accepted', models.IntegerField(default=0, verbose_name='通过数')),
                ('submit', models.IntegerField(default=0, verbose_name='提交数')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='知识点')),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name='难度')),
                ('is_delete', models.BooleanField(default=0, verbose_name='题目保护')),
                ('creator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='创建者')),
            ],
        ),
    ]
