# Generated by Django 3.2.4 on 2021-07-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to='files', verbose_name='用户头像'),
        ),
    ]
