# Generated by Django 3.2.3 on 2021-05-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_pri',
            field=models.IntegerField(choices=[(0, '超级管理员'), (1, '管理员'), (2, '教师'), (3, '志愿者'), (4, '用户')], default='4', verbose_name='权限'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('time', models.DateTimeField(verbose_name='创建时间')),
                ('importance', models.IntegerField(default=0, verbose_name='优先级')),
                ('defunct', models.BooleanField(default=0, verbose_name='是否失效')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='新闻图片')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='创建者')),
            ],
        ),
    ]
