# Generated by Django 3.2.4 on 2021-06-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_loginlog_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='solved',
        ),
        migrations.AddField(
            model_name='user',
            name='solved',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.problems', verbose_name='解决数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='submit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.solution', verbose_name='提交数量'),
        ),
    ]
