# Generated by Django 3.2.3 on 2021-05-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210524_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='新闻图片'),
        ),
    ]
