# Generated by Django 3.2.3 on 2021-06-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompileInfo',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='运行编号')),
                ('error', models.TextField(blank=True, null=True, verbose_name='编译错误原因')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False, verbose_name='竞赛编号')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='竞赛标题')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('defunct', models.BooleanField(default='0', verbose_name='是否屏蔽')),
                ('description', models.TextField(blank=True, null=True, verbose_name='竞赛描述')),
                ('private', models.BooleanField(default='1', verbose_name='是否公开')),
                ('lang_mask', models.IntegerField(default='1', verbose_name='竞赛语言')),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(verbose_name='竞赛编号')),
                ('problem_id', models.IntegerField(verbose_name='题目编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('num', models.IntegerField(verbose_name='竞赛题目编号')),
            ],
        ),
        migrations.CreateModel(
            name='CustomInput',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('input_text', models.TextField(null='True', verbose_name='输入测试数据')),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='登陆日志')),
                ('user_id', models.CharField(max_length=48, verbose_name='用户账号')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='登录IP')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='登入时间')),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('hash', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='主键')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('ua', models.CharField(max_length=255, verbose_name='浏览器相关的标识字符串')),
                ('refer', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问的上个页面的地址')),
                ('last_move', models.IntegerField(verbose_name='最后一次修改的时间')),
                ('first_time', models.IntegerField(blank=True, null=True, verbose_name='第一次访问的时间')),
                ('uri', models.CharField(blank=True, max_length=255, null=True, verbose_name='统一资源指示器')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False, verbose_name='帖子序号')),
                ('author_id', models.CharField(max_length=48, verbose_name='作者账号')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('topic_id', models.IntegerField(verbose_name='帖子分组')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '锁定'), (2, '删除')], verbose_name='论坛状态')),
                ('ip', models.GenericIPAddressField(verbose_name='发帖者地址')),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeInfo',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='运行编号')),
                ('error', models.TextField(blank=True, null=True, verbose_name='编译错误原因')),
            ],
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(verbose_name='solution_id')),
                ('sim_s_id', models.IntegerField(blank=True, null=True, verbose_name='与 s_id 相似的 solution_id')),
                ('sim', models.IntegerField(blank=True, null=True, verbose_name='相似度（50-100）')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='运行编号')),
                ('problem_id', models.IntegerField(verbose_name='问题编号')),
                ('user_id', models.CharField(max_length=48, verbose_name='用户编号')),
                ('time', models.IntegerField(verbose_name='运行时间')),
                ('memory', models.IntegerField(verbose_name='运行空间')),
                ('in_date', models.DateTimeField(verbose_name='加入时间')),
                ('result', models.IntegerField(verbose_name='运行结果')),
                ('language', models.IntegerField(verbose_name='所用语言')),
                ('ip', models.GenericIPAddressField(verbose_name='用户地址')),
                ('contest_id', models.IntegerField(blank=True, null=True, verbose_name='所属竞赛组')),
                ('valid', models.BooleanField(default='1', verbose_name='是否有效')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='代码在竞赛中的顺序号')),
                ('code_length', models.IntegerField(verbose_name='代码长度')),
                ('judge_time', models.DateTimeField(blank=True, null=True, verbose_name='判题时间')),
                ('pass_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='通过百分比')),
            ],
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False, verbose_name='运行编号')),
                ('source', models.TextField(blank='True', null='True', verbose_name='源代码')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False, verbose_name='论坛序号')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('top_level', models.IntegerField(default='0', verbose_name='置顶等级')),
                ('cid', models.IntegerField(blank=True, null=True, verbose_name='竞赛编号')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='竞赛中题目编号')),
                ('author_id', models.CharField(max_length=48, verbose_name='作者账号')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='team',
            name='defunct',
            field=models.BooleanField(default='0', verbose_name='是否屏蔽'),
        ),
        migrations.AlterField(
            model_name='news',
            name='importance',
            field=models.IntegerField(default=0, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='新闻编号'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user_id',
            field=models.CharField(max_length=48, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='problem_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='指导老师'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='团队成员'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='ip地址'),
        ),
    ]
