# Generated by Django 3.2.4 on 2021-07-05 07:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_user_maxim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.user_directory_path, verbose_name='用户头像'),
        ),
    ]
